spring.application.name=accordiq-api

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-autumn-pond-az9c1btt-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4KJDwipuUn9q
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Error messages
server.error.include-message=always